### ISSUE TITLE
stuck on Splash screens

### ISSUE THREAD

**Issue by ashasff0** [FerRiv3ra/rn-inkpad#1]
when i import anything from rn-inkpad in any file and reload the app it stuck on the splash screen but if the app was already loaded and try to import anything from rn-inkpad everything be fine  it only happen if i tried to load the app again im using expo go

**Comment by FerRiv3ra** [comment]
Hello @ashasff0 I can't be sure exactly what causes it to get stuck when you reload the app, I just did tests in Expo Go with two imported components and when I do a reload it continues to work fine without getting stuck on the splash screen as you can see in the next gif.

![2024-06-0814-04-27-ezgif com-video-to-gif-converter](https://github.com/FerRiv3ra/rn-inkpad/assets/58616200/217d5ba9-4fda-4e36-8516-077ab3427d03)

**Comment by ashasff0** [comment]
heyy hyd i hope you doing well well as you see here no matter what i do it always get stuck @FerRiv3ra 

![ezgif-1-a951c14083](https://github.com/FerRiv3ra/rn-inkpad/assets/137698307/0ed413be-6405-49f1-8f31-2e437878f401)

**Comment by FerRiv3ra** [comment]
I would dare to think that there is some problem with a related package, not so much with the library itself, you can send your package.json to see which packages are installed in your project

**Comment by ashasff0** [comment]
sure thing here you go @FerRiv3ra 
[package.json](https://github.com/user-attachments/files/15779341/package.json)

**Comment by Villefor** [comment]
Same, stuck on splash screen also (expo-go), works fine if i remove rk-inpad import. The component was ProgressBar

**Comment by FerRiv3ra** [comment]
@ashasff0 At first glance I see that you do not have @expo/vector-icons installed and that is a dependency on the library, make sure to follow the library [installation guide](https://rn-inkpad.web.app/docs/intro/).

@Villefor Check your package.json to see if it is the same detail with you.

**Comment by ashasff0** [comment]
@FerRiv3ra sadly that didnt solve it no...
{
  "name": "assaraya",
  "version": "1.0.0",
  "main": "expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web"
  },
  "dependencies": {
    "@expo/vector-icons": "^14.0.2",
    "@react-navigation/native": "^6.1.17",
    "@react-navigation/stack": "^6.3.29",
    "axios": "^1.7.2",
    "burnt": "^0.12.2",
    "expo": "~51.0.11",
    "expo-build-properties": "~0.12.3",
    "expo-image-picker": "~15.0.5",
    "expo-linear-gradient": "^13.0.2",
    "expo-local-authentication": "^14.0.1",
    "expo-status-bar": "~1.12.1",
    "firebase": "^10.12.2",
    "react": "18.2.0",
    "react-fancy-qrcode": "^1.0.3",
    "react-native": "0.74.2",
    "react-native-bouncy-checkbox": "^4.0.1",
    "react-native-document-picker": "^9.3.0",
    "react-native-gesture-handler": "^2.16.2",
    "react-native-otp-entry": "^1.7.0",
    "react-native-paper": "^5.12.3",
    "react-native-safe-area-context": "^4.10.4",
    "rn-inkpad": "^1.0.0"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@types/react": "~18.2.45",
    "typescript": "^5.1.3"
  },
  "private": true
}

**Comment by FerRiv3ra** [comment]
@ashasff0 That's quite strange, however, I wonder why you had to install that library manually since, according to the EXPO [documentation](https://docs.expo.dev/guides/icons/), that library already comes pre-installed with the framework.

**Comment by Villefor** [comment]
@FerRiv3ra I do, it came with expo, but i also manually installed based on Rk documentation

**Comment by FerRiv3ra** [comment]
I'm closing this issue because I've tested it on Expo and it works without any problem.
